version: "3.8"
services:
  reverse_proxy:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    depends_on:
      - ventav-backend
      - ventav-frontend
      - database
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - 80:80
    networks:
      - node-network  
  ventav-frontend:
    container_name: ventav-frontend
    image: ventav-frontend
    build: 
      context: ./ventav-frontend
    networks:
      - node-network  
  ventav-backend:
    container_name: ventav-backend
    hostname: ventav-backend
    image: ventav-backend
    build: 
      context: ./ventav-backend
    environment:
      MONGO_INITDB_DATABASE: ventav 
      MONGODB_URI: mongodb://db:27017
    depends_on:
      - database
    volumes:
      - ./db-data/mongo/:/data/database
    networks:
      - node-network
  database:
    container_name: db
    image: mongo
    restart: on-failure
    volumes:
      - ./mongodb:/data/database
    networks:
      - node-network  
volumes:
  dbdata6:
networks:
  node-network:
    external: true
    driver: bridge  